viewerImages=function(base,key,opts){var self=this;this.loaded=false;this.images=[];this.previewImages=[];this.count=4;this.loadedCount=0;this.previewLoadedCount=0;this.key=key;this.base=base;this.requestParams=" ";this.callbacks=[];if((opts!=undefined)&&(opts['count']!=undefined)){this.count=parseInt(opts['count']);}
this.onReady=function(callback){if(self.loaded){callback(self.images);}
self.callbacks.push(callback);};this.clearCallbacks=function(){self.callbacks=[];};this.loadImages=function(){for(var i=0;i<self.count;i++){var img=new Image();img.src=self.base+self.key+i.toString()+'.jpg'+requestParams;img.onload=self.imageOnload;self.images.push({"index":i,"image":img});}};this.loadPreview=function(){var previewImage=new Image();previewImage.src=self.base+self.key+'_preview'+'.jpg'+requestParams;previewImage.onerror=(function(){occipitalViewer.vi.loadImages()});previewImage.onload=(function(){var canvasPre=document.createElement("canvas");var ctxPre=canvasPre.getContext("2d");var offSet=previewImage.width/self.count;canvasPre.width=offSet;canvasPre.height=previewImage.height;for(var i=0;i<self.count;i++){ctxPre.drawImage(previewImage,offSet*i,0,offSet,previewImage.height,0,0,offSet,previewImage.height);var preFace=new Image();preFace.src=canvasPre.toDataURL("image/jpeg");preFace.onload=self.previewImageOnload;self.previewImages.push({"index":i,"image":preFace});}});}
this.imageOnload=function(num){self.loadedCount++;if(self.loadedCount==self.count){self.loaded=true;for(c in self.callbacks){self.callbacks[c](self.images);}}};this.previewImageOnload=function(num){self.previewLoadedCount++;if(self.previewLoadedCount==self.count){for(c in self.callbacks){self.callbacks[c](self.previewImages);}
occipitalViewer.vi.loadImages();}};};function init_vi(){if(!occipitalViewer.params.svc){occipitalViewer.params.svc="occipital"}
occipital_image_base="/viewer/images/"+occipitalViewer.params.svc[0];if(occipitalViewer.params.svc[0]=="o"){occipital_image_base="/images/viewer/";}
occipitalViewer.vi=new viewerImages(occipitalViewer.baseURL.substring(0,occipitalViewer.baseURL.length-1)+
occipital_image_base,occipitalViewer.params.iid,{'count':occipitalViewer.params.nf});}
function reset_occipitalviewer_vi(requestParams){if(!occipitalViewer.vi)
init_vi();self.loaded=false;}
function create_occipialviewer_vi(requestParams){if(!occipitalViewer.vi)
init_vi();self.requestParams=requestParams;occipitalViewer.vi.loadImages();}
function create_occipialviewer_vi_preview_optimized(requestParams){if(!occipitalViewer.vi)
init_vi();self.requestParams=requestParams;occipitalViewer.vi.loadPreview();};window.Modernizr=function(a,b,c){function z(a,b){for(var d in a)if(j[a[d]]!==c)return b=="pfx"?a[d]:!0;return!1}function y(a,b){return!!~(""+a).indexOf(b)}function x(a,b){return typeof a===b}function w(a,b){return v(m.join(a+";")+(b||""))}function v(a){j.cssText=a}var d="2.0.6",e={},f=b.documentElement,g=b.head||b.getElementsByTagName("head")[0],h="modernizr",i=b.createElement(h),j=i.style,k,l=Object.prototype.toString,m=" -webkit- -moz- -o- -ms- -khtml- ".split(" "),n={},o={},p={},q=[],r=function(a,c,d,e){var g,i,j,k=b.createElement("div");if(parseInt(d,10))while(d--)j=b.createElement("div"),j.id=e?e[d]:h+(d+1),k.appendChild(j);g=["&shy;","<style>",a,"</style>"].join(""),k.id=h,k.innerHTML+=g,f.appendChild(k),i=c(k,a),k.parentNode.removeChild(k);return!!i},s,t={}.hasOwnProperty,u;!x(t,c)&&!x(t.call,c)?u=function(a,b){return t.call(a,b)}:u=function(a,b){return b in a&&x(a.constructor.prototype[b],c)};var A=function(a,c){var d=a.join(""),f=c.length;r(d,function(a,c){var d=b.styleSheets[b.styleSheets.length-1],g=d.cssRules&&d.cssRules[0]?d.cssRules[0].cssText:d.cssText||"",h=a.childNodes,i={};while(f--)i[h[f].id]=h[f];e.csstransforms3d=i.csstransforms3d.offsetLeft===9},f,c)}([,["@media (",m.join("transform-3d),("),h,")","{#csstransforms3d{left:9px;position:absolute}}"].join("")],[,"csstransforms3d"]);n.canvas=function(){var a=b.createElement("canvas");return!!a.getContext&&!!a.getContext("2d")},n.webgl=function(){return!!a.WebGLRenderingContext},n.csstransforms3d=function(){var a=!!z(["perspectiveProperty","WebkitPerspective","MozPerspective","OPerspective","msPerspective"]);a&&"webkitPerspective"in f.style&&(a=e.csstransforms3d);return a};for(var B in n)u(n,B)&&(s=B.toLowerCase(),e[s]=n[B](),q.push((e[s]?"":"no-")+s));v(""),i=k=null,e._version=d,e._prefixes=m,e.testProp=function(a){return z([a])},e.testStyles=r;return e}(this,this.document);function importScript(url,callback){var tag=document.createElement("script");tag.type="text/javascript";if(typeof(tag.onload)!=="undefined"){tag.onload=callback;}else if(typeof(tag.onreadystatechange)!=="undefined"){tag.onreadystatechange=function(){if(callback&&(tag.readyState=='loaded'||tag.readyState=='complete')){callback();tag.onreadystatechange=function(){};}};}else{tag.setAttribute("onload","");tag.onload=callback;}
tag.src=url;document.body.appendChild(tag);return tag;}
viewerStart=function(){var viewerElement=document.getElementById("occipital-viewer");if(occipitalViewer.force_webgl||(Modernizr.webgl&&occipitalViewer.enable_webgl)){var html='<style type="text/css">'+'html, body{ margin: 0; width: 100%; height: 100%; }'+'canvas{ position:absolute; width: 100%; height: 100%; }'+'</style>'+'<canvas id="glCanvas"> If you are seeing this your web browser does not support the &lt;canvas&gt; element.</canvas>';viewerElement.innerHTML=html;canvas=document.getElementById("glCanvas");var create3DContext=function(canvas,opt_attribs){var names=["webgl","experimental-webgl","webkit-3d","moz-webgl"];var context=null;for(var ii=0;ii<names.length;++ii){try{context=canvas.getContext(names[ii],opt_attribs);}catch(e){}
if(context){break;}}
return context;}
var context=create3DContext(canvas,{});if(!context){Modernizr.webgl=false;viewerStart();}else{create_occipialviewer_vi_preview_optimized("?samedomain=true");importScript("/static/js/webglviewer.rNone.js")}}else if(Modernizr.csstransforms3d){var browser=navigator.userAgent;var notSupported=browser.indexOf("Chrome")!=-1&&browser.indexOf("CrMo")==-1;notSupported|=browser.indexOf("Firefox")!=-1&&(/Firefox\/(.\d)\./i).exec(browser)[1]<11;if(notSupported){Modernizr.csstransforms3d=false;viewerStart();}else{var html="<div class='viewport'>"+"<div class='panorama'>"+"<div class='rotation'></div>"+"<div class='calcmotionrot'></div></div></div>";viewerElement.innerHTML=html;importScript("/static/js/htmlviewer.r1333138605.js");create_occipialviewer_vi_preview_optimized("");}}else{var noFlashMessage=function(){document.getElementById('splashDiv').innerHTML=""+"<br><br><br><br><br><br><br> To view this panorma, <br> please update Flash to the latest version.<br><br>"+"<a href=\'http:\/\/www.adobe.com\/go\/getflash\'>  "+"<img src=\'http:\/\/www.adobe.com\/images\/shared\/download_buttons\/get_flash_player.gif\' alt=\'Get Adobe Flash player\' \/>"+"<\/a>";return;}
var embedFlash=function(){for(c in occipitalViewer.vi.callbacks)
occipitalViewer.vi.callbacks[c](null);window['flashIsReady']=function(){if(!occipitalViewer.isFlashLoaded){occipitalViewer.isFlashLoaded=true;}
if(occipitalViewer.isFlashLoaded&&occipitalViewer.isWrapperReady){occipitalViewer.wrapper.flashObject=document.getElementById('occipital-viewer');if(occipitalViewer.wrapper.isReadyCallback){occipitalViewer.wrapper.isReadyCallback();}}};window['flashDoneLoadingImages']=function(){if(occipitalViewer.wrapper.imagesLoadedCallback){occipitalViewer.wrapper.imagesLoadedCallback();}};window['error']=function(){noFlashMessage();};importScript("/static/js/flashviewer.r1333138606.js");viewerElement.id="occipital-viewer-content";var objectType="<object width=\'100%\' height=\'100%\' id=\'occipital-viewer\' class=\'viewerflash\' ";if(navigator.userAgent.indexOf("MSIE")==-1)
objectType+="type=\'application\/x-shockwave-flash\' data=\'\/static\/flash\/viewer.swf?v=36\'>";else{document.getElementById('interactionLayer').setAttribute("style","background-color:white; filter:alpha(opacity=0);");objectType+="classid=\'clsid:d27cdb6e-ae6d-11cf-96b8-444553540000\' align=\'middle\'>";}
occipitalViewer.loadEmbedSwfObject=function(){objectType+="<param name=\'FlashVars\' value=\'readyListener=window\' \/>"+"<param name=\'movie\' value=\'\/static\/flash\/viewer.swf?v=36\' \/>"+"<param name=\'quality\' value=\'high\' \/>"+"<param name=\'play\' value=\'true\' \/>"+"<param name=\'loop\' value=\'true\' \/>"+"<param name=\'wmode\' value=\'opaque\' \/>"+"<param name=\'scale\' value=\'noscale\' \/>"+"<param name=\'menu\' value=\'true\' \/>"+"<param name=\'devicefont\' value=\'false\' \/>"+"<param name=\'salign\' value=\'\' \/>"+"<param name=\'allowScriptAccess\' value=\'sameDomain\' \/>"+"<param name=\'time\' value=\'\' \/>"+"<\/object>";viewerElement.innerHTML=objectType;document.getElementById("occipital-viewer");};}
try{(new ActiveXObject('ShockwaveFlash.ShockwaveFlash')!=undefined)?embedFlash():noFlashMessage();}
catch(e){(navigator.mimeTypes["application/x-shockwave-flash"]!=undefined)?embedFlash():noFlashMessage();}}}
init_vi();importScript("http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.6.1.min.js",viewerStart);